// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF48b0fb9DecodeGithubComMatiXxDUrlShortenerInternalModels(in *jlexer.Lexer, out *UrlDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF48b0fb9EncodeGithubComMatiXxDUrlShortenerInternalModels(out *jwriter.Writer, in UrlDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UrlDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF48b0fb9EncodeGithubComMatiXxDUrlShortenerInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UrlDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF48b0fb9EncodeGithubComMatiXxDUrlShortenerInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UrlDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF48b0fb9DecodeGithubComMatiXxDUrlShortenerInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UrlDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF48b0fb9DecodeGithubComMatiXxDUrlShortenerInternalModels(l, v)
}
func easyjsonF48b0fb9DecodeGithubComMatiXxDUrlShortenerInternalModels1(in *jlexer.Lexer, out *URL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "baseUrl":
			out.BaseURL = string(in.String())
		case "shortUrl":
			out.ShortURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF48b0fb9EncodeGithubComMatiXxDUrlShortenerInternalModels1(out *jwriter.Writer, in URL) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"baseUrl\":"
		out.RawString(prefix[1:])
		out.String(string(in.BaseURL))
	}
	{
		const prefix string = ",\"shortUrl\":"
		out.RawString(prefix)
		out.String(string(in.ShortURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v URL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF48b0fb9EncodeGithubComMatiXxDUrlShortenerInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v URL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF48b0fb9EncodeGithubComMatiXxDUrlShortenerInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *URL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF48b0fb9DecodeGithubComMatiXxDUrlShortenerInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *URL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF48b0fb9DecodeGithubComMatiXxDUrlShortenerInternalModels1(l, v)
}
